name: Release

on:
  push:
    tags:
      - 'release-*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57

      - name: Build questions.db
        working-directory: ./questions
        run: make all

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: questions/questions.db